[tool.poetry]
name = "cseq"
version = "3.0.0"
description = "Bounded Verification of Multi-Threaded Programs via Lazy Sequentialization"
authors = ["Omar Inverso <omar.inverso@gssi.it>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
requests = "^2.26.0"
pytest = "^6.2.5"
pylint = "^2.11.1"
black = "^21.10b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
